extends Control

var maker = preload("res://Game/tank maker/tank maker.tscn")

var victoryMessages = [
	"The others had skill issue!",
	"Wiped the enemies!",
	"Can't be stopped!",
	"A born surviver!",
	"Survived the war!",
	"Didn't looked like a competition!",
	"Didn't cheated!",
	"Cheated...",
	"Master of tanks!",
	"Born to win!",
	"Better level up your game!",
	"Losing is the way of growth!",
	"Don't get mad!",
	"The enemies will remember this...",
	"Gamer for life!",
	"Be me: exist = win",
	"I have a life I promise",
	"Can't belive it!",
	"What a game!",
	"Was it close?",
	"Just another day!",
	"Just another game!",
	"Still winning!",
	"Relaaaax... relax",
	"This was just the trainning",
	"A professionnal!",
	"Are you even gonna read it?",
	"Your gonna have a bad time",
	"Teleported to victory!",
	"???",
	"!!!",
	"?",
	"!?",
	"I... have no words...",
	"... oh, your still here...",
	"Last game",
	"If night: sleep",
	"Take a break from time to time",
	"Can't predict my bullet?!",
	"It's about the journey, not the destination",
	"Getting better!",
	"Master of the controls!",
	"Picked all the OP power ups!",
	"Blinded the oponents!",
	"They couln't see it coming!",
	"Played many bullets hell before!",
	"The project of the ouest uh?",
	"The game is alive",
	"Hey! Another win!",
	"This was just a walk",
	"HOMERUN!!!",
	"Out of the park!",
	"15 points!",
	"Unbelivable!",
	"Everybody is watching you!",
	"Picked the meta!",
	"What. Just. Happened?",
	"They were the 7 and the others the 9",
	".-- --- .--",
	"WoW!",
	"༼ つ ◕_◕ ༽つ",
	"＞﹏＜",
	"ヾ≧▽≦*)o",
	"GG EZ",
	"Easy, wasn't it?",
	"Another one bites the dust",
	"That's how it's done.",
	"Plot twist: I'm good!",
	"Plot twist: I'm god",
	"A legend is born!",
	"Victory is the only option.",
	"I have 3 million power in WAR",
	"History repeats itself",
	"Got'em!",
	"Another W",
	"Outplayed!",
	"I'm a professional!",
	"The prophecy was true",
	"This league is mine LOL",
	"WWW",
	"Clip that!",
	"The cake is the truth",
	"What a save!",
	"This is my final form",
	"I'll be back!",
	"God aim",
	"Playing 5D chess!",
	"Playing 5D gold!",
	"Checkmate!",
	"I knew that you knew",
	"ERROR",
	"You died.",
	"Game over!",
	"You unlocked a new character (fake)",
	"Easy Mode is now unlocked (no)",
	"Listen!",
	"Barrel roll",
	"The summit is high",
	"All I know is that I must be good",
	"Victory screen is real!",
	"GG",
	"You're the only one to blame",
	"Don't hate the player...",
	"Better luck next time",
	"I'm invicible!",
	"F in the chat",
	"Achievement unlocked: Win!",
	"99% skill",
	"404",
	"200 OK",
	"Still standing... again",
	"Who doesn't wanna win?",
	"That time where I was teleported to another world to find the special game but it was too easy so the anime couldn't be done as we don't have enough watch time... part 6",
	"Well played!",
	"Unstoppable!!",
	"Winning streak!",
	"UPGRADEDUPGRADEDUPGRADEDUPGRADEDUPGRADEDUPGRADEDBASIC is fire!",
	"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
	"Walked the walk",
	"Incredible!",
	"Just like the 80s",
	"Just before Y2K",
	"Killing spree",
	"Tomorrow, more tanks will fall, where are we even going?..",
	"See you after life",
	"Gamed like a gamer",
	"Good aim?",
	"Flawless",
	"Standing above all!",
	"No contest"
]


func _ready() -> void:
	var makerInstance = maker.instantiate()
	makerInstance.scale = Vector2.ONE * 3
	%winningTankPreview.add_child(makerInstance)
	victoryMessages.append("I wrote " + str(victoryMessages.size()) + " messages...")

func setup(winner):
	%winningTankPreview.get_child(0).modulate = global.playersColors[winner-1]
	%winningTankPreview.get_child(0).make(global.playersData[winner-1].evolutionID)
	%PlayerDisp.text = "player " + str(winner)
	%VictoryMessage.text = "\"" + victoryMessages[randi_range(0, victoryMessages.size()-1)] + "\""

func _on_button_pressed() -> void:
	get_tree().change_scene_to_file("res://Main menu/Menu.tscn")
